### ISSUE TITLE
Exception encountered when attempting to active drills with void both enabled.

### ISSUE THREAD

**Issue by tgkgate** [Allen-Wrench/AutoRemoveStone#2]
2023-04-12 18:55:15.639 - Thread:   1 ->  Exception occurred: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at AutoRemoveStone.StoneRemover.Update()
   at Sandbox.Game.World.MyUpdateCallback.Update()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
[log.txt](https://github.com/Allen-Wrench/AutoRemoveStone/files/11216967/log.txt)

**Comment by Allen-Wrench** [comment]
Thanks for the heads up, I'll take a look when I get home from work tonight.

**Comment by tcasey27** [comment]
Confirmed issue using void both.

Exception occurred: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at AutoRemoveStone.StoneRemover.Update()
